import { type Plugin } from 'vite';
import fs from 'node:fs';
import path from 'node:path';
import { generateThemeFromCssVariables } from "./generateThemeFromCssVariables";

/**
 * ----------------------------------------------------------------------
 * css-variables-to-theme-object-vite-plugin
 * ----------------------------------------------------------------------
 * Watches a source file (e.g. tokens.css) and generates a plain .ts
 * file containing theme object and type declarations.
 *
 * Kept as .ts (not .d.ts) so it can be imported normally, e.g.:
 *   import type { Color, FontSize } from './tokens.ts';
 *   import { theme } from './tokens.ts';
 *
 * * HOT RELOAD NOTE:
 *  * Because the generated file has real runtime exports, it's a normal
 *  * node in Vite's module graph — Vite's own dev server watcher already
 *  * watches it (it's a real project file) and already knows how to HMR it
 *  * correctly when it changes (walk importers, patch an accept boundary,
 *  * or fall back to full reload). We don't touch that path at all.
 *  *
 *  * The only thing Vite *doesn't* know about on its own is the source file
 *  * (tokens.css) — nothing imports it, so nothing would trigger a rebuild
 *  * when it changes. That's what `addWatchFile` + `handleHotUpdate` below
 *  * are for: on a source-file change, regenerate the .ts file on disk, and
 *  * let Vite's normal file watcher pick up *that* write on its own. We
 *  * `return []` only for the source-file event itself, since the source
 *  * file has no module counterpart to reload.
 *  * ----------------------------------------------------------------------
 *  */

export interface Options {
  /** CSS file path (relative to project root) */
  sourceCssFilePath: string;

  /**
   * Where to write the generated .ts file. Relative to project root.
   * Defaults to the source css file folder..
   */
  outputTsFilePath?: string;
}

function generate( sourceCssFileContent: string ): string {
  return `// Auto-generated by vite-plugin-tokens — do not edit by hand
export const theme = ${JSON.stringify(generateThemeFromCssVariables(sourceCssFileContent))};
`;
}

export default function cssVariablesToThemeObjectVitePlugin({ sourceCssFilePath, outputTsFilePath = sourceCssFilePath }: Options): Plugin {
  let { dir: sourceCssFileDir, name: sourceCssFileName, ext: sourceCssFileExtension } = path.parse(sourceCssFilePath);
  let { dir: outputTsFileDir, name: outputTsFileName, ext: outputTsFileExtension } = path.parse(outputTsFilePath);
  let sourceCssFileAbsolutePath: string;
  let outputTsFileAbsolutePath: string;

  function regenerate() {
    const sourceCssFileContent = fs.readFileSync(sourceCssFileAbsolutePath, 'utf-8');
    const outputTsFileContent = generate(sourceCssFileContent);

    fs.mkdirSync(path.dirname(outputTsFileAbsolutePath), { recursive: true });
    fs.writeFileSync(outputTsFileAbsolutePath, outputTsFileContent, 'utf-8');
  }

  return {
    name: 'css-variables-to-theme-object-vite-plugin',

    configResolved({ root: configAbsolutePath }) {
      sourceCssFileAbsolutePath = path.resolve(configAbsolutePath, sourceCssFileDir, `${sourceCssFileName}${sourceCssFileExtension}`);
      outputTsFileAbsolutePath = path.resolve(configAbsolutePath, outputTsFileDir, `${outputTsFileName}${outputTsFileExtension}`);
    },

    buildStart() {
      // Registers sourcePath as a watched dependency even though nothing
      // actually imports it. Works correctly for both `vite dev` and
      // `vite build --watch`, unlike manually reaching into
      // server.watcher.
      this.addWatchFile(sourceCssFileAbsolutePath);
      regenerate();
    },

    handleHotUpdate(ctx) {
      if (path.normalize(ctx.file) !== path.normalize(sourceCssFileAbsolutePath)) return;

      regenerate();

      // No module in the JS graph depends on the generated file (it's
      // type-only, erased before anything reaches the browser), so
      // there's nothing to hot-patch. Returning [] tells Vite "handled,
      // do nothing" and suppresses the full-page-reload it would
      // otherwise trigger by default for a watched file it can't map to
      // a module.
      return [];
    },
  };
}