import { describe, expect, it } from "vitest";

import { generatePropertiesListFromDescriptors } from "../generators/generatePropertiesListFromDescriptors";

describe("generatePropertiesListFromDescriptors", () => {
  it("should generate a list of css properties from descriptors", () => {
    const result = generatePropertiesListFromDescriptors({
      descriptors: [
        {
          properties: [
            "margin",
            "marginInline",
            "marginInlineStart",
            "marginInlineEnd",
            "marginBlock",
            "marginBlockStart",
            "marginBlockEnd",
          ],
        },
        {
          properties: [
            { name: "gridTemplateColumns", shortcut: "columns" },
            { name: "gridTemplateAreas", shortcut: "areas" },
            { name: "gridTemplateRows", shortcut: "rows" },
            { name: "gridAutoRows", shortcut: "autoRows" },
            { name: "gridColumn", shortcut: "column" },
            { name: "gridArea", shortcut: "area" },
            { name: "gridRow", shortcut: "row" },
          ],
        },
      ],
      theme: {
        breakpoints: {
          sm: "40em",
          md: "48em",
          lg: "64em",
          xl: "80em",
          xxl: "96em",
        },
      },
    });
    expect(result).toMatchInlineSnapshot(`
      [
        "margin",
        "sm:margin",
        "md:margin",
        "lg:margin",
        "xl:margin",
        "xxl:margin",
        "marginInline",
        "sm:marginInline",
        "md:marginInline",
        "lg:marginInline",
        "xl:marginInline",
        "xxl:marginInline",
        "marginInlineStart",
        "sm:marginInlineStart",
        "md:marginInlineStart",
        "lg:marginInlineStart",
        "xl:marginInlineStart",
        "xxl:marginInlineStart",
        "marginInlineEnd",
        "sm:marginInlineEnd",
        "md:marginInlineEnd",
        "lg:marginInlineEnd",
        "xl:marginInlineEnd",
        "xxl:marginInlineEnd",
        "marginBlock",
        "sm:marginBlock",
        "md:marginBlock",
        "lg:marginBlock",
        "xl:marginBlock",
        "xxl:marginBlock",
        "marginBlockStart",
        "sm:marginBlockStart",
        "md:marginBlockStart",
        "lg:marginBlockStart",
        "xl:marginBlockStart",
        "xxl:marginBlockStart",
        "marginBlockEnd",
        "sm:marginBlockEnd",
        "md:marginBlockEnd",
        "lg:marginBlockEnd",
        "xl:marginBlockEnd",
        "xxl:marginBlockEnd",
        "gridTemplateColumns",
        "sm:gridTemplateColumns",
        "md:gridTemplateColumns",
        "lg:gridTemplateColumns",
        "xl:gridTemplateColumns",
        "xxl:gridTemplateColumns",
        "columns",
        "sm:columns",
        "md:columns",
        "lg:columns",
        "xl:columns",
        "xxl:columns",
        "gridTemplateAreas",
        "sm:gridTemplateAreas",
        "md:gridTemplateAreas",
        "lg:gridTemplateAreas",
        "xl:gridTemplateAreas",
        "xxl:gridTemplateAreas",
        "areas",
        "sm:areas",
        "md:areas",
        "lg:areas",
        "xl:areas",
        "xxl:areas",
        "gridTemplateRows",
        "sm:gridTemplateRows",
        "md:gridTemplateRows",
        "lg:gridTemplateRows",
        "xl:gridTemplateRows",
        "xxl:gridTemplateRows",
        "rows",
        "sm:rows",
        "md:rows",
        "lg:rows",
        "xl:rows",
        "xxl:rows",
        "gridAutoRows",
        "sm:gridAutoRows",
        "md:gridAutoRows",
        "lg:gridAutoRows",
        "xl:gridAutoRows",
        "xxl:gridAutoRows",
        "autoRows",
        "sm:autoRows",
        "md:autoRows",
        "lg:autoRows",
        "xl:autoRows",
        "xxl:autoRows",
        "gridColumn",
        "sm:gridColumn",
        "md:gridColumn",
        "lg:gridColumn",
        "xl:gridColumn",
        "xxl:gridColumn",
        "column",
        "sm:column",
        "md:column",
        "lg:column",
        "xl:column",
        "xxl:column",
        "gridArea",
        "sm:gridArea",
        "md:gridArea",
        "lg:gridArea",
        "xl:gridArea",
        "xxl:gridArea",
        "area",
        "sm:area",
        "md:area",
        "lg:area",
        "xl:area",
        "xxl:area",
        "gridRow",
        "sm:gridRow",
        "md:gridRow",
        "lg:gridRow",
        "xl:gridRow",
        "xxl:gridRow",
        "row",
        "sm:row",
        "md:row",
        "lg:row",
        "xl:row",
        "xxl:row",
      ]
    `);
  });
});
